In [ ]:
import numpy as np

A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

C = np.dot(A, B)  # Ou C = A @ B

print(C)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
# using np.matmul()
C_matmul = np.matmul(A, B)

# using usando np.dot()
C_dot = np.dot(A, B)

# using operator "@"
C_at = A @ B

print("Result using np.matmul():\n", C_matmul)
print("Result using np.dot():\n", C_dot)
print("Result using operator '@':\n", C_at)


Result using np.matmul():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Result using np.dot():
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Result using operator '@':
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [5]:
# Compute the (0,0) element manually
result_00 = (A[0, 0] * B[0, 0]) + (A[0, 1] * B[1, 0]) + (A[0, 2] * B[2, 0])

# Print the result
print("Element (0,0) of the product matrix:", result_00)

Element (0,0) of the product matrix: 6


In [ ]:
import numpy as np

def matrix_product(A, B):
    # Get dimensions of A and B
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    
    # Ensure matrix multiplication is valid (columns of A must match rows of B)
    if cols_A != rows_B:
        raise ValueError("Number of columns in A must match the number of rows in B.")

    # Initialize result matrix with zeros
    C = np.zeros((rows_A, cols_B))

    # Compute each element of the result matrix
    for i in range(rows_A):  # Iterate through rows of A
        for j in range(cols_B):  # Iterate through columns of B
            for k in range(cols_A):  # Iterate through columns of A / rows of B
                C[i, j] += A[i, k] * B[k, j]  # Multiply and sum

    return C

# Compute the matrix product
C = matrix_product(A, B)

# Print result
print("Matrix product of A and B:\n", C)


Matrix product of A and B:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [8]:
import numpy as np

def matrix_product(A, B):
    # Get dimensions of A and B
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    
    # Ensure matrix multiplication is valid
    if cols_A != rows_B:
        print(f"Error: Cannot multiply matrices of shape {A.shape} and {B.shape}.")
        print("The number of columns in the first matrix must match the number of rows in the second matrix.")
        return None  # Return None to indicate failure

    # Initialize result matrix with zeros
    C = np.zeros((rows_A, cols_B))

    # Compute each element of the result matrix
    for i in range(rows_A):  # Iterate through rows of A
        for j in range(cols_B):  # Iterate through columns of B
            for k in range(cols_A):  # Iterate through columns of A / rows of B
                C[i, j] += A[i, k] * B[k, j]  # Multiply and sum

    return C

# Define incompatible matrices D and E
D = np.array([[-1, 2, 3], [4, -5, 6]])
E = np.array([[-9, 8, 7], [6, -5, 4]])

# Attempt to compute the matrix product
result = matrix_product(D, E)

# Print the result if multiplication was successful
if result is not None:
    print("Matrix product of D and E:\n", result)


Error: Cannot multiply matrices of shape (2, 3) and (2, 3).
The number of columns in the first matrix must match the number of rows in the second matrix.


In [11]:
import numpy as np

# Transpose of E
E_transposed = E.T

# Product of D by E transposed
result = np.matmul(D, E_transposed)

print(result)


[[ 46  -4]
 [-34  73]]
